### PR TITLE
More german spelling corrections and translations

### PR DESCRIPTION
**Pull request by brussell1**
-corrected some overlooked spelling errors
-I forgot some files last time, added them now
-fixed the first line in WORLDMAP.MSG

### CODE REVIEW

**Comment by fedprod** [comment]
You **do** know that Fallout 1 and two used the old german spelling reform, right?
So everything vanilla will stick out like a sore tooth^^"

**Comment by brussell1** [comment]
Argghhh!
I was under the impression that the german mod contains all msg files...
Sorry for this mess.

We have two options now:
1. Reverting every commit I've made regarding text changes
2. I'll change the remaining vanilla text files to new spelling rules and add them here. That would be: 
dialog/BOSLORI.MSG
dialog/GHOUL.MSG
dialog/JUNKDOG.MSG
dialog/RAIDGRD.MSG
dialog/DARL.MSG
dialog/HHOOKER.MSG
dialog/LORRIAN.MSG
dialog/ASSBLOW.MSG
dialog/GENLOCK.MSG
dialog/JER.MSG
dialog/LORRI.MSG
game/EDITOR.MSG
game/ITEM.MSG
game/SCRIPT.MSG
game/STAT.MSG

What do you say?

**Comment by Lexx2k** [comment]
Well, it could be turned into a separate mod like "German - Remastered" or something. Keep in mind, however, that not all .msg files from Fo1 are used in ettu. Due to various script changes, etc. by Fixt, some stuff was changed.

**Comment by wipe2238** [comment]
As someone who knows like total 5 words in german (at best) i'm gonna jump in :D and say - why not finish it, if you're up for the task? What i gathered from Lexx on IRC is that old spelling had a nostalgia feel but not much more than that.

Seeing that this is a mod for 20y.o. game, and young players are still _discovering_ vanilla Fallouts, why not let them have spelling they're familiar with. I'm trying to apply old rules in my own language to Fallout but that just doesn't click. At same time i'd say completely opposite if this would be mod for Arcanum, or some medieval game - there it could be actually an advantage.

**Comment by brussell1** [comment]
Well, I've added the possibly missing files.

**Pull request merged**
