### PR TITLE
Translation Update

### PR DESCRIPTION
**Pull request by fedprod**
The finishline is in sight.
Some finishing touches, more consistent writeups of terms, comprehension and readability, one or two not translated graphics, maybe integrating the blood patch, checking out the Invasions, etc.
But translationwise I would say it's about 99% done. =)

### CODE REVIEW

**Comment by fedprod** [comment]
Also discuss: Boodpatch Y/N? Because US Version obviously doesn't need it, and it would be about 226MB extra Art assets in the folder...

**Comment by Lexx2k** [comment]
> Also discuss: Bloodpatch Y/N?
> US Version obviously doesn't need it, and it would be about 226MB extra Art assets in the folder...

No. If at all then Bloodpatch must be its own mod. I was already thinking about doing it, but as you said, it's ~200mb more which most of the people do not need anymore nowadays, so I'd rather not add it to this repo.
I thought of putting it into its own repo, but then realized that this is kinda useless... might as well just download the existing bloodpatch, because it wouldn't work that much different.

**Comment by fedprod** [comment]
Yes, you remember correctly that it is cut
Problem is, the audio stream is inside the MVE file, so it would be in english then... 
I remember that there where a project some thime ago, to get sfall understand AVIs.
I *think* I remember someone cutting them together, but can't find it on the fly...

**Comment by fedprod** [comment]
Oh, and of course another problem rears it's head there:
/DATA/ART/CUTS seems to superseede any later paths. I jsut dropped the english version into fo1_german/DATA/ART/CUTS and it was still in german and censored...
Even of it's not hardcoded, what I come to believe, we would have to supply BOTH versions, MEH!
So that's ~128MB (INTRO.MVE and OVERRUN.MVE, wich was also csensored it seems)

**Comment by Lexx2k** [comment]
> Problem is, the audio stream is inside the MVE file, so it would be in english then...

Well, someone has to rip the audio from the german video and put it over the english. Shouldn't be too hard to do, but I personally don't really want to handle this.

**Comment by fedprod** [comment]
Well, if we have the tools somewhere, it shouldn't be too bad, but I don't know that we have^^"

**Pull request merged**
